vars:
  - _variables.manual.yml

stages:
  join:
    cmd: >
      lyscripts data join 
      -i data/2021-usz-oropharynx.csv
      data/2021-clb-oropharynx.csv
      data/2023-isb-multisite.csv
      data/2023-clb-multisite.csv
      data/2024-hvh-oropharynx.csv
      -o data/joined.csv
    deps:
    - data/2021-clb-oropharynx.csv
    - data/2021-usz-oropharynx.csv
    - data/2023-clb-multisite.csv
    - data/2023-isb-multisite.csv
    - data/2024-hvh-oropharynx.csv
    outs:
    - data/joined.csv

  enhance:
    cmd: >
      lyscripts data enhance
      --params _variables.manual.yml
      data/joined.csv data/enhanced.csv
    deps:
    - data/joined.csv
    params:
    - _variables.manual.yml:
        - modalities
    outs:
    - data/enhanced.csv

  filter:
    cmd: lyscripts data filter data/enhanced.csv data/filtered.csv --include-subsites C01 C09 C10
    deps:
    - data/enhanced.csv
    outs:
    - data/filtered.csv

  reduce:
    cmd: python scripts/reduce.py data/filtered.csv data/reduced.csv
    deps:
    - data/filtered.csv
    - scripts/reduce.py
    outs:
    - data/reduced.csv

  sampling:
    matrix:
      model: [simple, full]
    cmd: >
      lyscripts sample
      --input data/reduced.csv
      --params models/${item.model}/params.yaml
      --output models/${item.model}/samples.hdf5
      --history models/${item.model}/history.csv
      --walkers-per-dim ${sampling.walkers_per_dim}
      --check-interval ${sampling.check_interval}
      --trust-fac ${sampling.trust_fac}
      --rel-thresh ${sampling.rel_thresh}
      --nsteps ${sampling.nsteps}
      --thin ${sampling.thin}
      --cores ${sampling.cores}
    deps:
    - data/reduced.csv
    - requirements.in
    params:
    - models/${item.model}/params.yaml:
    outs:
    - models/${item.model}/samples.hdf5
    - models/${item.model}/history.csv:
        cache: false

  compute-priors:
    matrix:
      model: [simple, full]
      scenario: [priors]
    cmd: >
      lyscripts compute priors
      --samples models/${item.model}/samples.hdf5
      --priors models/${item.model}/priors.hdf5
      --params models/${item.model}/params.yaml
      --scenarios scenarios/${item.scenario}.yaml
    deps:
    - models/${item.model}/samples.hdf5
    params:
    - models/${item.model}/params.yaml:
    - scenarios/${item.scenario}.yaml:
    outs:
    - models/${item.model}/${item.scenario}.hdf5

  compute-prevalences:
    matrix:
      model: [full]
      scenario: [overall, with_ipsi, with_upstream]
    cmd: >
      lyscripts compute prevalences
      --priors models/${item.model}/priors.hdf5
      --prevalences models/${item.model}/prevalences_${item.scenario}.hdf5
      --data data/reduced.csv
      --params models/${item.model}/params.yaml
      --scenarios scenarios/${item.scenario}.yaml
    deps:
    - models/${item.model}/priors.hdf5
    - data/reduced.csv
    params:
    - models/${item.model}/params.yaml:
    - scenarios/${item.scenario}.yaml:
    outs:
    - models/${item.model}/prevalences_${item.scenario}.hdf5

  compute-midext-prevalences:
    cmd: >
      python scripts/compute_midext_prevalences.py
    deps:
    - models/full/samples.hdf5
    - data/reduced.csv
    params:
    - models/full/params.yaml:
    outs:
    - models/full/prevalences_midext.hdf5

  compute-posteriors:
    cmd: >
      lyscripts compute posteriors
      --priors models/full/priors.hdf5
      --posteriors models/full/posteriors.hdf5
      --params models/full/params_risks.yaml
      --scenarios scenarios/risks.yaml
    deps:
    - models/full/priors.hdf5
    params:
    - models/full/params_risks.yaml:
    - scenarios/risks.yaml:
    outs:
    - models/full/posteriors.hdf5

  compute-risks:
    cmd: >
      lyscripts compute risks
      --posteriors models/full/posteriors.hdf5
      --risks models/full/risks.hdf5
      --params models/full/params_risks.yaml
      --scenarios scenarios/risks.yaml
    deps:
    - models/full/posteriors.hdf5
    params:
    - models/full/params_risks.yaml:
    - scenarios/risks.yaml:
    outs:
    - models/full/risks.hdf5

  plot-figures:
    matrix:
      name:
        - model_burnin_history
        - model_midext_evo
        - model_prevalences_midext
        - model_prevalences_overall
        - model_prevalences_upstream
        - model_prevalences_with_ipsi
        - model_risks
        - model_state_dist
        - data_strat
        - data_upset_ipsi
    cmd: >
      python scripts/${item.name}.py
    deps:
    - scripts/${item.name}.py
    - scripts/shared.py
    - scripts/paths.py
    - requirements.txt
    - models
    outs:
    - figures/fig_${item.name}.svg:
        persist: true
        cache: false

  compile-variables:
    cmd: >
      python scripts/compile_variables.py
      --output _variables.dynamic.yml
    deps:
    - scripts/compile_variables.py
    - data/reduced.csv
    outs:
    - _variables.dynamic.yml

  concat-variables:
    cmd: >
      cat _variables.manual.yml _variables.dynamic.yml > _variables.yml
    deps:
    - _variables.manual.yml
    - _variables.dynamic.yml
    outs:
    - _variables.yml

  render-pdf:
    cmd: >
      quarto render manuscript.qmd --to nature-pdf
    deps:
    - models
    - figures
    - data/reduced.csv
    - manuscript.qmd
    - _variables.yml
    outs:
    - .output/manuscript.pdf
    - .output/_tex/manuscript.tex
