version: 1

########################################################################################
# This dictionary defines which LNLs are present in the
# graph and how they are connected. In this case, the
# primary tumors spreads to the LNLs II, III and IV.
# Subsequently, level II spreads to III and III to IV.
graph:
  tumor:
    T: [I, II, III, IV, V]
  lnl:
    I: [II]
    II: [III]
    III: [IV]
    IV: [V]
    V: []

########################################################################################
# Below are some parameters necessary for the model setup:
model:
  class: Midline
  kwargs:
    is_symmetric:
      tumor_spread: false
      lnl_spread: true
    use_central: false
    use_midext_evo: true
    use_mixing: true
  distributions:                # marginalize over diagnosis times. Keys are T-stages
    early:
      frozen: binomial
      max_time: 10
      kwargs: {p: 0.3}
    late:
      parametric: binomial
      max_time: 10
  modalities: [max_llh]         # List of modalities, defined further down
  mapping:
    0: "early"
    1: "early"
    2: "early"
    3: "late"
    4: "late"

########################################################################################
# Under this key we define the specficity and sensitivity for a range
# of diagnostic modalities. They are taken from literature and during
# sampling, everything that's not commented our here will be used for
# inference.
modalities:
  max_llh: [1.0, 1.0]
